/* English copy for the local education preview. Mathematical symbols stay intact. */
'use strict';
globalThis.VortexEnglish={
 'Przezroczystość płaszczyzny między torusami':'Transparency of the plane between tori',
 'Płaszczyzna między torusami':'Plane between tori',
 'Złoty dysk oznacza fragment płaszczyzny odniesienia w połowie odległości środków torusów. Dla symetrycznego rozstawu leży na Z = 7; jego promień dopasowuje się do większego torusa. Warstwa pojawia się razem z torusami.':'The golden disk shows a portion of the reference plane halfway between the torus centers. With symmetric spacing it lies at Z = 7; its radius follows the larger torus. This layer appears together with the tori.',
 'Pełny pokaz · konstrukcja i wiry · Piramida 11:7':'Full show · construction and vortices · Pyramid 11:7',
 'Etap 14 · pokaz edukacyjny':'Stage 14 · educational show',
 'Konstrukcja i wiry na wspólnej scenie':'Construction and vortices in one scene',
 'Pięć odsłon na jednym zegarze. Piramida B = 11, h = 7; powierzchnie zr = 1, odbicie w Z = 7 i rzeczywiste owale. Torusy są osobnymi obiektami artystycznymi; nie wyprowadzono ich jako przekształcenia powierzchni ani rozwiązania przepływu.':'Five stages on one clock. Pyramid B = 11, h = 7; surfaces zr = 1, reflection across Z = 7 and actual oval sections. The tori are separate artistic objects; no derivation makes them a transformation of the surfaces or a flow solution.',
 'Wspólna scena':'Shared scene',
 'Sterowanie pokazem':'Show controls',
 'Widok perspektywiczny':'Perspective view',
 'Widok konstrukcyjny · równoległy 3D':'Construction view · orthographic 3D',
 'Widok z boku · XZ':'Side view · XZ',
 'Widok z góry · XY':'Top view · XY',
 'Piramida 11:7, dwie lustrzane powierzchnie hiperboliczne, płaszczyzny, rzeczywiste przekroje oraz dwa przeciwbieżne torusy':'Pyramid 11:7, two mirrored hyperbolic surfaces, planes, actual sections and two counter-rotating tori',
 'T1: θ+ ↺, ψ+ · linie ciągłe':'T1: θ+ ↺, ψ+ · solid lines',
 'T2: θ− ↻, ψ− · linie przerywane':'T2: θ− ↻, ψ− · dashed lines',
 'Pełny pokaz':'Full show',
 'Odtwórz':'Play',
 'Pauza':'Pause',
 'Pełna scena · 100%':'Full scene · 100%',
 'Kadr do nagrania':'Recording view',
 'Przebieg pokazu':'Show progress',
 'Ograniczony ruch · klatki ręczne':'Reduced motion · manual frames',
 'Powolny obrót kamery':'Slow camera rotation',
 'Reset kamery':'Reset camera',
 'Widok':'View',
 'Równoległy 3D':'Orthographic 3D',
 'Z boku · XZ':'Side · XZ',
 'Z góry · XY':'Top · XY',
 'Kadr kamery':'Camera framing',
 'Stały · piramida zachowuje rozmiar':'Fixed · pyramid keeps its size',
 'Dopasuj całe stożki':'Fit complete cones',
 'Jakość':'Quality',
 'Niska · telefon':'Low · phone',
 'Średnia':'Medium',
 'Wysoka':'High',
 'Ustawienie':'Preset',
 'Czytelna konstrukcja':'Clear construction',
 'Nagranie · wszystkie warstwy':'Recording · all layers',
 'Skala stożków hiperbolicznych względem V':'Hyperbolic cone scale about V',
 'Przywróć skalę · 5,5%':'Restore scale · 5.5%',
 'Widok jak na ilustracji':'Match the reference view',
 'Zakres powierzchni':'Surface extent',
 'Ku nieskończoności · jak na ilustracji':'Toward infinity · reference view',
 'Całe wycinki z podstawami':'Complete patches with bases',
 'Otoczenie przekrojów':'Around the sections',
 'Skala 0,5–200% zmienia wyłącznie oba lustrzane stożki, ich płaszczyzny i rzeczywiste przekroje. W stałym kadrze piramida, torusy i kamera zachowują rozmiar. Duże powierzchnie mogą wychodzić poza kadr, jak na ilustracji. Osobna opcja kamery „Dopasuj całe stożki” obejmuje całość; +/− zmienia tylko przybliżenie kamery. Zmiana skali zatrzymuje pokaz.':'The 0.5–200% scale changes only the two mirrored cones, their planes and actual sections. In fixed framing, the pyramid, tori and camera retain their size. Large surfaces may extend beyond the frame, as in the reference. The separate “Fit complete cones” camera option includes the entire geometry; +/− changes only camera zoom. Changing scale pauses the show.',
 'Kierunki i wielkości wirów':'Vortex directions and sizes',
 'Stożek 1 · kierunek':'Cone 1 · direction',
 'Stożek 2 · kierunek':'Cone 2 · direction',
 'Domyślny':'Default',
 'Lustrzany domyślny':'Mirrored default',
 'Odwrócony':'Reversed',
 'Torus 1 · kierunek':'Torus 1 · direction',
 'Torus 2 · kierunek':'Torus 2 · direction',
 'Wielkość torusa 1':'Torus 1 size',
 'Wielkość torusa 2':'Torus 2 size',
 'Odległość środków torusów [u]':'Torus center distance [u]',
 'Domyślne wiry':'Default vortices',
 'Kierunek torusa odwraca oba obiegi θ i ψ. Rozmiar skaluje R i r równomiernie; rozstaw przesuwa środki symetrycznie względem Z = 7. Stożki i piramida zachowują geometrię. Domyślne wiry przywracają rozmiar 100%, rozstaw 4 u i zaakceptowane kierunki. Zmiana kierunku, rozmiaru lub rozstawu zatrzymuje pokaz — użyj „Odtwórz”.':'Torus direction reverses both θ and ψ rotations. Size scales R and r uniformly; spacing moves the centers symmetrically about Z = 7. The cones and pyramid keep their geometry. Default vortices restores 100% size, 4 u spacing and the accepted directions. Changing direction, size or spacing pauses the show — use “Play”.',
 'Złote jaja i przezroczystość':'Golden Eggs and transparency',
 'Złote jajo 1 · pełna bryła':'Golden Egg 1 · full solid',
 'Złote jajo 2 · pełna bryła':'Golden Egg 2 · full solid',
 'Przezroczystość jaja 1':'Egg 1 transparency',
 'Przezroczystość jaja 2':'Egg 2 transparency',
 'Przezroczystość stożka 1':'Cone 1 transparency',
 'Przezroczystość stożka 2':'Cone 2 transparency',
 'Jaja są bryłami obrotowymi rzeczywistego owalu wokół jego długiej osi. Zachowują skalę stożków; przy 5,5% są małe. Zwiększ skalę, aby obejrzeć bryły. 100% przezroczystości ukrywa daną bryłę lub siatkę; 0% przywraca jej pełną intensywność. Przekroje i płaszczyzny mają osobne przełączniki.':'The eggs are solids formed by revolving the actual oval about its long axis. They keep the cone scale; at 5.5% they are small. Increase the scale to inspect the solids. 100% transparency hides the selected solid or wireframe; 0% restores its full intensity. Sections and planes have separate toggles.',
 'Piramida':'Pyramid',
 'Linie konstrukcyjne':'Construction lines',
 'Powierzchnie stożków':'Cone surfaces',
 'Płaszczyzny cięcia':'Cutting planes',
 'Rzeczywiste przekroje':'Actual sections',
 'Torusy':'Tori',
 'Obiegi i kierunki':'Paths and directions',
 'Cząstki i smugi torusów':'Torus particles and trails',
 'Spirale po stożkach':'Cone spirals',
 'Oznaczenia':'Labels',
 'Efekty i pomiary':'Effects and measurements',
 'Prędkość obiegu':'Rotation speed',
 'Gęstość cząstek':'Particle density',
 'Długość smug [s obiegu]':'Trail length [rotation seconds]',
 'Poświata':'Glow',
 'Zmierz 30 nieruchomych klatek':'Measure 30 still frames',
 'Wyczyść pomiary':'Clear measurements',
 'Przeciągnięcie, strzałki lub przybliżenie wyłączają automatyczny obrót. Na telefonie użyj przycisków +/− i przesuwaj scenę jednym palcem. Pauza zatrzymuje pokaz, cząstki i kamerę. Suwak wybiera nieruchomą klatkę; po 100% odtwarzanie utrzymuje obieg do pauzy.':'Dragging, arrow keys or zooming turns off automatic rotation. On a phone, use +/− and drag the scene with one finger. Pause stops the show, particles and camera. The slider selects a still frame; after 100%, playback keeps the particles circulating until paused.',
 'Przybliż kamerę':'Zoom in',
 'Oddal kamerę':'Zoom out',
 'Nagraj demo · 26 s':'Record demo · 26 s',
 'Zakończ nagranie':'Stop recording',
 'Pobierz nagranie WebM':'Download WebM recording',
 'Geometria i granice interpretacji':'Geometry and limits of interpretation',
 'Zachowano wariant A, α = atan(14/11), z₀ = 7,65. Domyślne torusy mają środki Z = 5 i 9, R = 2,4 oraz r = 0,65; suwaki pozwalają zmienić ich rozmiar i rozstaw. Domyślny widok ilustracji używa q = 0,055. Suwak q stosuje istniejące jednolite skalowanie względem V; 100% odpowiada konstrukcji L = h. Zakresy z wcześniejszego podglądu pozwalają wybrać otwarte powierzchnie ku nieskończoności albo całe wycinki z okrągłymi podstawami. Okręgi oznaczają granice rysowanej siatki: nieskończona powierzchnia zr = 1 nie ma skończonej podstawy. Owal pozostaje rzeczywistym przecięciem, nie elipsą. L/W dla 11:7 pozostaje poza 0,1% od φ. Drugi układ jest odbiciem Z ↦ 14 − Z. Domyślny ruch jego cząstek także jest lustrzany, bez dodatkowego odwracania czasu; niezależne przełączniki pozwalają odwrócić każdy wir. Spirale są artystycznymi trajektoriami po powierzchniach, niezależnymi od torusów i bez solvera przepływu.':'Variant A, α = atan(14/11) and z₀ = 7.65 are preserved. Default tori have centers at Z = 5 and 9, R = 2.4 and r = 0.65; sliders change their size and spacing. The reference view defaults to q = 0.055. The q slider uses the existing uniform scaling about V; 100% corresponds to L = h. Surface extents from the earlier preview offer open surfaces toward infinity or complete patches with circular bases. The circles mark the drawn mesh boundaries: the infinite surface zr = 1 has no finite base. The oval remains the actual intersection, not an ellipse. For 11:7, L/W remains outside 0.1% of φ. The second system is reflected by Z ↦ 14 − Z. Its default particle motion is also mirrored, without an additional time reversal; independent selectors can reverse each vortex. The spirals are artistic paths on the surfaces, independent of the tori and without a flow solver.',
 'Konstrukcja i przeniesienie etapu 9':'Stage 9 construction and transfer',
 'Zachowany pokaz wirów':'Original vortex show',
 'Uruchomienie i nagranie':'Launch and recording instructions (Polish)',
 'Koncepcja: Michał Przybylski —':'Concept: Michał Przybylski —',
 'Koncepcja: Michał Przybylski — prylski.dev':'Concept: Michał Przybylski — prylski.dev',
 'Wróć do sterowania · Esc':'Return to controls · Esc',
 'Odwróć głębię':'Reverse depth',
 'Pełny ekran':'Full screen',
 'Wyjdź z pełnego ekranu':'Exit full screen',
 'Odtwórz scenę':'Play scene',
 'Pauza sceny':'Pause scene',
 'Siła głębi':'Depth strength',
 'Prawe oko':'Right eye',
 'Lewe oko':'Left eye',
 'Cross-eye: skrzyżuj wzrok, aby połączyć dwa punkty w środkowy obraz. Lewy kadr jest dla prawego oka, prawy dla lewego. ':'Cross-eye: cross your eyes to merge the two dots into a central image. The left frame is for your right eye, the right frame for your left eye. ',
 'Odwrócona głębia · kolejność oczu zamieniona. ':'Reversed depth · eye order swapped. ',
 'Na telefonie wygodniej w poziomie; zmniejsz siłę głębi, jeśli trudno połączyć obrazy.':'On a phone, landscape is easier; reduce depth strength if the images are hard to fuse.',
 '1 / Piramida 11:7 i linie konstrukcyjne.':'1 / Pyramid 11:7 and construction lines.',
 '2 / Pierwsza powierzchnia, płaszczyzna i rzeczywisty przekrój.':'2 / First surface, plane and actual section.',
 '3 / Lustrzany układ · szeroka część ku górze.':'3 / Mirrored system · wide part facing upward.',
 '4 / Dwa torusy i wybrane kierunki θ oraz ψ.':'4 / Two tori and selected θ and ψ directions.',
 '5 / Pełna wspólna scena · wirujące cząstki.':'5 / Full shared scene · swirling particles.',
 'Wizualizacja artystyczna przeciwbieżnych wirów toroidalnych':'Artistic visualization of counter-rotating toroidal vortices',
 'Wizualizacja artystyczna':'Artistic visualization',
 'przeciwbieżnych wirów toroidalnych':'of counter-rotating toroidal vortices',
 'podstawa dolna · wycinek':'lower base · patch',
 'podstawa górna · wycinek':'upper base · patch',
 'linie ciągłe':'solid lines',
 'linie przerywane':'dashed lines',
 'Ograniczony ruch · wybieraj nieruchome klatki suwakiem.':'Reduced motion · select still frames with the slider.',
 'Pokaz w ruchu · następnie ciągły obieg.':'Show playing · continuous circulation follows.',
 'Obieg cząstek · Pauza zatrzyma wszystkie wiry.':'Particles circulating · Pause stops all vortices.',
 'Pauza · ręczna kontrola kierunków i warstw.':'Paused · manual control of directions and layers.',
 'Kamera filmowa włączona · działa podczas odtwarzania w widoku 3D.':'Automatic camera enabled · active during playback in 3D view.',
 'Kamera filmowa zatrzymana · ponowne uruchomienie wymaga włączenia.':'Automatic camera stopped · enable it to restart.',
 'Nagranie zapisuje wyłącznie scenę z podpisem do pliku WebM, bez dźwięku. Nie wysyła pliku.':'Recording saves only the scene and caption to a silent WebM file. It does not upload the file.',
 'Ta przeglądarka nie obsługuje nagrywania Canvas. Skorzystaj z instrukcji w education/README.md.':'This browser does not support Canvas recording. See education/README.md for instructions (Polish).',
 'Ograniczony ruch jest włączony. Wyłącz go świadomie, aby nagrać animację.':'Reduced motion is enabled. Turn it off deliberately to record animation.',
 'Brak kodera WebM.':'No WebM encoder available.',
 'Gotowy plik WebM':'WebM file ready',
 'Nagranie częściowe · pokaz nie dotarł do finału':'Partial recording · the show did not reach the finale',
 'Pobierz go poniżej.':'Download it below.',
 'Nie udało się przygotować pliku do pobrania. Powtórz nagranie w widocznej karcie.':'Could not prepare the download. Record again with the tab visible.',
 'Nagrywanie 26 s: pięć odsłon i 6 s finału. Esc kończy wcześniej.':'Recording 26 s: five stages and a 6 s finale. Esc stops early.',
 'Nagranie nie powstało:':'No recording was created:',
 'Użyj instrukcji ręcznej.':'Use the manual instructions.',
 'Odległość środków musi wynosić 2–8 u.':'Center distance must be 2–8 u.',
 'Niepoprawny rozmiar lub kierunek torusa.':'Invalid torus size or direction.',
 'Parametry cięcia muszą być skończone.':'Cutting parameters must be finite.',
 'Parametry efektów muszą być skończone.':'Effect parameters must be finite.',
 'Skala q musi wynosić 0,005–2.':'Scale q must be 0.005–2.',
 'Niepoprawna jakość lub gęstość cząstek.':'Invalid particle quality or density.',
 'Niepoprawna faza, deformacja lub liczba cząstek.':'Invalid phase, deformation or particle count.',
 'Niepoprawne parametry spirali powierzchni.':'Invalid surface spiral parameters.',
 'Prędkość musi wynosić 0,25–3×.':'Speed must be 0.25–3×.',
 'Brak odrębnego zamkniętego owalu: wymagane 0 < α < 90° oraz z₀² > 4k tan α (k = 1).':'No separate closed oval: requires 0 < α < 90° and z₀² > 4k tan α (k = 1).',
 'Odległość środków d=':'Center distance d=',
 'szczelina osiowa':'axial gap',
 'zakresy wysokości torusów nakładają się':'torus height ranges overlap',
 'Ustawienia interaktywne; domyślne wartości zachowują zaakceptowany układ.':'Interactive settings; defaults preserve the accepted arrangement.',
 'błąd względem φ':'error relative to φ',
 'próg 0,1%':'0.1% threshold',
 'Zgodność w granicach tolerancji modelu.':'Within the model tolerance.',
 'Poza tolerancją modelu.':'Outside the model tolerance.',
 'Przekrój jest owalem, nie elipsą.':'The section is an oval, not an ellipse.',
 'Efektywna jakość:':'Effective quality:',
 'niska':'low',
 'średnia':'medium',
 'wysoka':'high',
 'cząstek łącznie':'particles in total',
 'obiekt':'object',
 'Rysowanie':'Drawing',
 'sceny':'scene',
 'mediana':'median',
 'próbek':'samples',
 'To czas CPU rysowania, nie pełny czas klatki.':'This is CPU drawing time, not the full frame time.'
};
